rule preprocess:
    resources:
        mem_mb=12000,
        runtime=30

rule create_training_sets:
    resources:
        mem_mb=20000,
        runtime=10

rule train_models_RNN:
    resources:
        mem_mb=32000,
        runtime=MODEL_PARAMS["max_epochs"]*120,
        slurm_extra="--gres=gpu:1"
 
rule sample_molecules_RNN:
    resources:
        mem_mb=1000,
        runtime=MODEL_PARAMS["sample_mols"]//10000,
        slurm_extra="--gres=gpu:1"

rule tabulate_molecules:
    resources:
        mem_mb=4000,
        runtime=MODEL_PARAMS["sample_mols"]//1000,

rule write_structural_prior_CV:
    resources:
        mem_mb=32000,
        runtime=180

rule write_formula_prior_CV:
    resources:
        mem_mb=32000,
        runtime=180
