name: Build Package and Test it

on:
  push:
    branches: [ master, pyproject]
  pull_request:
    branches: [ master, pyproject ]

jobs:
  build_wheels:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]

    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@master

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.10'

    - name: Build source
      run: pip install .

    - name: Install developer dependencies
      run: pip install .[dev]

    - name: Pytest
      run: pytest

